test-config-version:
  1.3

test-password: 
  '{cipher}281269725541fa360b69b16f99ee822cf8d971caee666877fe72c795103e93fa'

test-rsa:
  '{cipher}AQCAJ2wlBeC97Q44ojc5VfF3mt3XPSQEgV8wtSUYekGqi38kZO/bkp2pxdBtmSLghHUTYcALy2yqSqN0AmQURTFgGcJZ/40QaFLdGwrsffa3LtFmJkAINtWFSR8yhy+IFWJzpm8SKQyxeFIIUHAXtglm3yuE5ZvoNBEwSc7Z0olv9fdu2+ppKSLxqHZDpSRtEgjfqlzASoLXiwHlFv3rtP0kCQMqQfRkBmsrjr2idEmbyGFAPCdE95y0LRGWJgBBZThTCArIflX10fL5yu7ZcK1/B8fTWHtW0RM7e4DUwd3bmwkSE6j/E/jNhQvxbLULqIefOsGr3LNO2nm8hVNsyM6qjwdJvBNNZzY0ylR9l7Oj5ZWt1PeuGc9nx7kXs04wG/o='
